schema_version: 1

context:
  name: webdriver-manager
  version: "4.1.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/webdriver_manager-${{ version }}.tar.gz
  sha256: e209637837731b6cd9dccf79784868eedce8c4a35258076762dbe5e7f8d83ba4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - packaging
    - python >=${{ python_min }}
    - python-dotenv
    - requests
    - tqdm

tests:
  - python:
      imports:
        - webdriver_manager
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Library provides the way to automatically manage drivers for different browsers
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/SergeyPirogov/webdriver_manager

extra:
  recipe-maintainers:
    - thewchan
